version: '3.7'
services:      
  innova_back:
    build: 
      context: repos/innova_core
    container_name: innova_core
    restart: always
    ports: 
      - 9090:9090
    volumes:
      - ./logs_core:/usr/app/logs:rw 
    networks:
      - net
volumes: 
  schemas: {}
networks:
  net: