version: '3.7'
services:
  mysql:
    build: 
      context: db
    container_name: mysql
    restart: always
    ports: 
      - 23306:3306  
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "innova_core"
      MYSQL_USER: "innova"
      MYSQL_PASSWORD: "1234"
    volumes:
      - ./db/schemas:/var/lib/mysql:rw
    networks:
      innova_network:
        aliases: 
          - mysql_host
volumes: 
  schemas: {}
networks:
  innova_network:
    name: innova_net
    driver: bridge